### ISSUE TITLE
IP?

### ISSUE THREAD

**Issue by jojoe77777** [LegoCraftPE/Issues#1]
Issue: I don't know the IP.... >:P

**Comment by legoboy0215** [comment]
? You mean server IP?
play.legocraft.me
Not complete yet. I am building LCPE 2.0.0 which adds HG and new kits.

**Comment by jojoe77777** [comment]
k

**Comment by jojoe77777** [comment]
also... I CAN'T GET TO PM FORUMS! WAHHHH

**Comment by UltimateMcraft** [comment]
Pointless 😛
