### ISSUE TITLE
Skeleton heads -_-

### ISSUE THREAD

**Issue by UltimateMcraft** [LegoCraftPE/Issues#10]
How many do we need?
They are duplicated in inventory

![screenshot_20151205-182618](https://cloud.githubusercontent.com/assets/6726237/11608586/7dbc264e-9b7e-11e5-8e17-bbb0a0a419ad.png)

**Comment by legoboy0215** [comment]
ImagineMine bug.

**Comment by jojoe77777** [comment]
@UltimateMcraft You have a REALLY big screen.

**Comment by legoboy0215** [comment]
Win 10?

**Comment by UltimateMcraft** [comment]
Lol sorry, couldn't be bothered to reply zzzz... No I use android
