### ISSUE TITLE
The site is down... (legocraft.me)

### ISSUE THREAD

**Issue by UltimateMcraft** [LegoCraftPE/Issues#13]
When will it be back up?

**Comment by legoboy0215** [comment]
Today. I crashed my web server.

**Comment by PocketKiller** [comment]
you edited Xenforo files wrongly? burn...

**Comment by legoboy0215** [comment]
No.

**Comment by legoboy0215** [comment]
I removed GLIBC.

**Comment by UltimateMcraft** [comment]
GLIBC? It comes up with Mysql errors when I visit

**Comment by legoboy0215** [comment]
Yes. Because the old VPS can't be used. New VPS is setup already/
